---
- name: Ansible Test Playbook
  #hosts: aws_region_us_east_2
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
   - {role: e2inventory}
   - {role: rdsinventory}
   - {role: vpcsubinventory} 
