---
- hosts: localhost
  name: ec2 script
  connection: local
  become: yes
  become_user: sudo
  tasks:
    - name: execute python script
      script: files/ec2-inv.py
    - name: Ensure recepient email identity exists
      aws_ses_identity:
        identity: dhanashree.dbfree@gmail.com
        region: us-east-2
        state: present
      register: sendyes
    - name: Send email with attachment based on conditions
      when: sendyes
      script: files/send-mail.py
