---
- name: execute python script
    #command: chmod +x etc/ansible/inventory/csvtocsv.py
  become: true
  become_user: centos
  args:
    chdir: /etc/ansible/aws-inventory/ec2-inventory
  script: files/ec2-inv.py
     #shell: python3 /etc/ansible/447721165257/447721165257/roles/ec2inventory/files/ec2-inv.py

- name: Ensure recepient email identity exists
  aws_ses_identity:
    identity: dhanashree.dbfree@gmail.com
    region: us-east-2
    state: present
  register: sendyes
- name: Send email with attachment based on conditions
  when: sendyes
  become: true
  become_user: centos
  args:
    chdir: cd /etc/ansible/aws-inventory/ec2-inventory
  script: files/send-mail.py
     #shell: python3 /etc/ansible/447721165257/447721165257/roles/ec2inventory/files/send-mail.py
