---
- name: Ansible playbook for EC2 inventory
  hosts: localhost
  connection: local
  become: yes
  become_user: root
  vars_prompt:
    - name: "Enter password for Centos user"
      prompt: "Enter password"
      private: yes
  tasks:
    - name: Execute Python script for fetching and generating inventory
      script: files/ec2-inv.py
    - name: Ensure recepient email identity exists
      aws_ses_identity:
        identity: dhanashree.dbfree@gmail.com
        region: us-east-2
        state: present
      register: sendyes
    - name: Execute Python script for fetching and generating inventory
      script: files/ec2-inv.py
