---
- name: Ansible Test Playbook
  #hosts: aws_region_us_east_2
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
   - name: execute python script
     #command: chmod +x etc/ansible/inventory/csvtocsv.py
     shell: python3 /etc/ansible/447721165257/447721165257/roles/vpcsubinventory/files/vpc-sub-inv.py

   - name: Ensure recepient email identity exists
     aws_ses_identity:
       identity: dhanashree.dhamgunde@zensar.com
       state: present
     register: recyes
   - name: Ensure recepient email identity exists
     aws_ses_identity:
       identity: dhanashree.dbfree@gmail.com
       state: present
     register: sendyes
   - name: Send email with attachment based on conditions
     when: sendyes and recyes
     shell: python3 /etc/ansible/447721165257/447721165257/roles/vpcsubinventory/files/send-mail.py
