---
- name: Ansible Test Playbook
  tasks:
   - name: execute python script
     #command: chmod +x etc/ansible/inventory/csvtocsv.py
     script: files/rds-inv.py
     #shell: python3 /etc/ansible/447721165257/447721165257/roles/rdsinventory/files/rds-inv.py

   - name: Ensure recepient email identity exists
     aws_ses_identity:
       identity: dhanashree.dhamgunde@zensar.com
       state: present
     register: recyes
   - name: Ensure recepient email identity exists
     aws_ses_identity:
       identity: dhanashree.dbfree@gmail.com
       state: present
     register: sendyes
   - name: Send email with attachment based on conditions
     when: sendyes and recyes
     script: files/send-mail.py
     #shell: python3 /etc/ansible/447721165257/447721165257/roles/rdsinventory/files/send-mail.py
